name: expense_tracker
description: A cross-platform expense tracker app.

# Prevent the package from being accidentally published to pub.dev
publish_to: 'none'

# Application version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
     sdk: flutter
  fl_chart: ^0.69.2 

  intl: ^0.17.0
  cupertino_icons: ^1.0.6 # iOS-style icons


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Recommended lints for better coding practices


  test_api: 0.7.3
  


flutter:
  uses-material-design: true

  