name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Flutter Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'

      # Step 3: Set up Dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Run Tests
      - name: Run Flutter tests
        run: flutter test

      # Step 5: Analyze the Code
      - name: Analyze code
        run: flutter analyze

      # Step 6: Build the APK
      - name: Build APK
        run: flutter build apk --release

      # Step 7: Upload APK as an Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
